model:
  col2node_config:
    type: col2node
    f_n_hidden: 2
    f_hidden_size: 512
    g_n_hidden: 2
    g_hidden_size: 512
    output_size: 256
    activation_function: LeakyReLU
  graph_sage_config:
    hidden_channels: 256
    num_layers: 3
    out_channels: 32
data:
  train_dataset_size: 1024
  train_batch_size: 4
  val_dataset_size: 512
  val_batch_size: 64
training:
  num_epochs: 1000