model:
  type: gbdsim
  col2node_config:
    type: col2node
    f_n_hidden: 2
    f_hidden_size: 512
    g_n_hidden: 3
    g_hidden_size: 512
    output_size: 512
    activation_function: ReLU
  graph_sage_config:
    hidden_channels: 512
    num_layers: 1
    out_channels: 256
  similarity_head_strategy: nn
data:
  train_dataset_size: 10000
  train_batch_size: 16
  val_dataset_size: 1024
  val_batch_size: 64
training:
  num_epochs: 1000
  learning_rate: 0.0001
  weight_decay: 0.0