model:
  type: gbdsim
  col2node_config:
    type: col2node
    f_n_hidden: 1
    f_hidden_size: 1024
    g_n_hidden: 3
    g_hidden_size: 256
    output_size: 512
    activation_function: LeakyReLU
  graph_sage_config:
    hidden_channels: 512
    num_layers: 3
    out_channels: 256
data:
  train_dataset_size: 2048
  train_batch_size: 32
  val_dataset_size: 512
  val_batch_size: 64
training:
  num_epochs: 1000