model:
  type: gbdsim
  col2node_config:
    type: col2node
    f_n_hidden: 2
    f_hidden_size: 1024
    g_n_hidden: 3
    g_hidden_size: 512
    output_size: 1024
    activation_function: LeakyReLU
  graph_sage_config:
    hidden_channels: 1024
    num_layers: 3
    out_channels: 256
data:
  train_dataset_size: 10000
  train_batch_size: 16
  val_dataset_size: 1024
  val_batch_size: 64
training:
  num_epochs: 1000